export const workflowPhases = [
  {
    phase: "Phase 1 - AI Idea Explorer",
    purpose: "Define creative direction and select the strongest campaign concept.",
    input: "Project intent and market context.",
    output: "Approved Creative Brief.",
    approvalGate: "✓ CREATIVE BRIEF APPROVED",
    artifact: "p1_idea",
    nextConsumer: "Content Creator",
  },
  {
    phase: "Phase 2 - Content Creator",
    purpose: "Translate the brief into platform-ready content packaging.",
    input: "Approved Creative Brief.",
    output: "Approved Content Package.",
    approvalGate: "✓ CONTENT PACKAGE READY",
    artifact: "p2_content",
    nextConsumer: "Viral Scanner",
  },
  {
    phase: "Phase 3 - Viral Scanner",
    purpose: "Evaluate content strength and lock production recommendations.",
    input: "Approved Content Package.",
    output: "Approved Viral Review.",
    approvalGate: "✓ CONTENT APPROVED FOR PRODUCTION",
    artifact: "p3_viralReview",
    nextConsumer: "Production Studio",
  },
  {
    phase: "Phase 4 - AI Production Studio",
    purpose: "Build the final production manifest for creative execution.",
    input: "Approved Viral Review.",
    output: "Approved Production Manifest.",
    approvalGate: "✓ PRODUCTION MANIFEST READY",
    artifact: "p4_production",
    nextConsumer: "Publishing",
  },
  {
    phase: "Phase 5 - Publishing",
    purpose: "Dispatch approved campaign payload to the selected channel.",
    input: "Approved Production Manifest.",
    output: "Dispatched Publishing Payload.",
    approvalGate: "✓ PUBLISHING PAYLOAD DISPATCHED",
    artifact: "p5_publishing",
    nextConsumer: "AI Content Intelligence",
  },
  {
    phase: "Phase 6 - AI Content Intelligence",
    purpose: "Capture outcomes and strategic learnings from live performance.",
    input: "Dispatched Publishing Payload and campaign metrics.",
    output: "Finalized Intelligence Summary.",
    approvalGate: "✓ INTELLIGENCE CYCLE COMPLETE",
    artifact: "p6_intelligence",
    nextConsumer: "Next Campaign Brief",
  },
  {
    phase: "Phase 7 - Next Creative Cycle",
    purpose: "Start the next campaign with inherited intelligence context.",
    input: "Finalized Intelligence Summary.",
    output: "New creative brief with strategic continuity.",
    approvalGate: "Workflow restart from Idea Explorer",
    artifact: "p1_idea (next cycle)",
    nextConsumer: "Content Creator",
  },
];
